In [2]:
import numpy as np
arr=np.array([1,2,3,4,5,4,6,4])
print (arr)
x=np.where (arr==4)
print(x)

[1 2 3 4 5 4 6 4]
(array([3, 5, 7]),)


In [3]:
arr=np.array ([1,2,3,4,5,6,7,8])
x=np.where (arr%2==0)
print (arr)
print(x)

[1 2 3 4 5 6 7 8]
(array([1, 3, 5, 7]),)


In [5]:
#sorting the array
arr=np.array([3,2,0,1])
print ("\n original array:",arr)
arr=np.array([[3,2,4],[5,0,1]])
print("\n original array:",arr)
print("\n sorted array",np.sort(arr))


 original array: [3 2 0 1]

 original array: [[3 2 4]
 [5 0 1]]

 sorted array [[2 3 4]
 [0 1 5]]


In [14]:
import numpy as np 
Sorted_array=np.array([1,3,5,7])
values=[2,4,6]
insert_indices=np.searchsorted(Sorted_array,values)
print (Sorted_array)
print(values)
print(insert_indices)

[1 3 5 7]
[2, 4, 6]
[1 2 3]


In [18]:
#Filter
arr=np.array([41,42,43,44])
x=[True,False,True,False]
newarr=arr[x]
print("\nOriginal array:",arr)
print("\nFilter index:",x)
print("\nFilter array:",newarr)


Original array: [41 42 43 44]

Filter index: [True, False, True, False]

Filter array: [41 43]


In [23]:
arr=np.array([41,42,43,44])
filter_arr=arr>42
newarr=arr[filter_arr]
print("\nOriginal array:",arr)
print("\nFilter array:condition->42:",filter_arr)
print("\nNew array:",newarr)


Original array: [41 42 43 44]

Filter array:condition->42: [False False  True  True]

New array: [43 44]
